export const unspecified1 = {
    G_assess_pith: null,
    G_assess_rank_base: null,
    G_coeff_buy: null,
    G_coeff_sell: null,
    G_e_name: null,
    G_elapse_pith: null,
    G_featured_col: null,
    G_has_no_child: null,
    G_name: "指定なし",
    G_parent_code: null,
    G_price_pitch: null,
    G_tier: null,
    PK: "genre1",
    SK: "",
  }

  export const unspecified2 = {
    G_assess_pith: null,
    G_assess_rank_base: null,
    G_coeff_buy: null,
    G_coeff_sell: null,
    G_e_name: null,
    G_elapse_pith: null,
    G_featured_col: null,
    G_has_no_child: null,
    G_name: "指定なし",
    G_parent_code: null,
    G_price_pitch: null,
    G_tier: null,
    PK: "genre2",
    SK: "",
  }

  export const unspecified3 = {
    G_assess_pith: null,
    G_assess_rank_base: null,
    G_coeff_buy: null,
    G_coeff_sell: null,
    G_e_name: null,
    G_elapse_pith: null,
    G_featured_col: null,
    G_has_no_child: null,
    G_name: "指定なし",
    G_parent_code: null,
    G_price_pitch: null,
    G_tier: null,
    PK: "genre3",
    SK: "",
  }