export const items = {
  MAINTITLE: "新規商品承認",
  NEWPRODUCTIMPORTLIST: "新規商品取込一覧",
  INPUTDATE: "取込日付",
  COMPANY: "提供会社",
  IMPORTLIST: "取込一覧",
  OUTSIDEPRODUCTIMPORTLIST: "外部商品手動取込",
  OUTSIDEPRODUCTTYPE: "外部商品ファイル種別",
  SELECTFILE: "ファイル選択",
  IMPORTTYPE: "取込種別",
  IMPORTHISTORYLIST: "外部商品ファイル取込履歴表示",
  CATEGORIZING: "商品分類",
  REGISTERATION: "商品登録",
  EDIT: "商品編集",
  LIST: "新規商品取込一覧",
  LIST2: "新規商品一覧",
  SEARCH: "検索",
  INPUTNUMBER: "取込番号",
  INPUTDATE: "取込日付",
  COMPANY: "提供会社",
  IMPORTLIST: "取込一覧",
  NEWPRODUCTINFO: "新規商品情報",
  DUPLICATEPRODUCTINFO: "重複商品情報",
  COUNT: "件数",
  NEWPRODUCTIMPORTDETAIL: "新規商品詳細",
  F1DETAIL: "F1 詳細",
  F2CREATE: "F2 新規",
  F3UPDATE: "F3 更新",
  F4DELETE: "F4 破棄",
  F11CONFIRM: "F11 確定",
  F12BACK: "F12 戻る",
  UPDATECATEGORY: "更新区分",
  STG_ENV: "stg環境",
  DEV_ENV: "dev環境",
  DELETE: "削除",
};

export const number = {
  NUM1: 1,
  NUM2: 2,
  NUM3: 3,
  NUM4: 4,
  NUM5: 5,
  AUTHORNAME_MAXLENGTH: 256,
  AUTHORNAME_KANA_MAXLENGTH: 256,
  AUTHORNAME_EN_MAXLENGTH: 256,
  COMMENT_ATTACHEDDISPLAY_MAXLENGTH: 256,
  COMMENT_MAXLENGTH: 2000,
};

// export const login = {
//   LOGIN: "ログイン",
//   MAIN: "ブックオフコーポレーション <br /> 統合ログインシステム",
// };
